### ISSUE TITLE
Ruby group capstone: set up your Kanban board

### ISSUE THREAD

**Issue by Bondok6** [aimemalaika/catalog-ruby#31]
# Hello there 🙋‍♂️,

### Thanks for taking the time to review our project.

<hr/>

- This is the [link](https://github.com/aimemalaika/catalog-ruby/projects/1) to our Kanban Board.
- We are 3 team members.
- Team member 1 is @eduardosancho .
- Team member 2 is @aimemalaika .
- Team member 3 is @Bondok6 .

**Comment by FrederickMih** [comment]
Hi Team, 

# Congratulations! :tada: :tada: 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
